ChatBot
YelyzavetaSydorova/NIX_java_education_Sydorova_Yelyzaveta pull request #2
Opened 2021-10-15 15:07 UTC by YelyzavetaSydorova

Second pull request for merge

2021-10-16 11:39 UTC, MaximSomochkin requested changes

2021-10-16 11:39 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +        label:
Не используй метки НИКОГДА -  это рудимент. Перепиши код с использованем if-else и break;

2021-10-17 10:30 UTC, asrubel commented on src/nix/education/java/chatbot/ChatBot.java
> +            int answer = scanner.nextInt();
Лучше проинициализировать переменную до цикла и в цикле ее менять

2021-10-19 20:51 UTC, asrubel approved these changes

2021-10-20 14:01 UTC, merged